app:
  incoming:
    rest:
      port: ${APP_PORT:-8080}

database:
  url: ${DATABASE_URL:-"postgres://user:password@localhost:5432/notification_center_db"}
  max_connections: ${DB_MAX_CONNECTIONS:-10}
